frontend/urls.py
from django.urls import path, include
from django_distill import distill_path

from frontend import views
from frontend.types import UrlMap
from frontend.views import get_services_list

app_name = 'frontend'


urls_maps: list[UrlMap] = [{
    'url': '',
    'view': views.index_view,
    'name': 'index',
    'distill_file': 'index.html',
}, {
    'url': '',
    'view': views.index_view,
    'name': 'home',
    'distill_file': 'home.html',
}, {
    'url': 'about',
    'view': views.about_view,
    'name': 'about',
    'distill_file': 'about.html'
}, {
    'url': 'testimonials',
    'view': views.testimonials_view,
    'name': 'testimonials',
    'distill_file': 'testimonials.html'
}, {
    'url': 'contact',
    'view': views.contact_view,
    'name': 'contact',
    'distill_file': 'contact.html'
}, {
    'url': 'services/<slug:slug>',
    'view': views.services_view,
    'name': 'services',
    'distill_file': 'services/{}.html',
    'distill_func': get_services_list,
}]

static_page_urlpatterns = []

for url_map in urls_maps:
    static_page_urlpatterns.append(path(url_map['url'], url_map['view'], name=url_map['name']))
    distill_path_kwargs = {
        'name': url_map['name'],
    }
    if url_map.get('distill_file'):
        distill_path_kwargs['distill_file'] = url_map['distill_file']
    if url_map.get('distill_func'):
        distill_path_kwargs['distill_func'] = url_map['distill_func']

    static_page_urlpatterns.append(
        distill_path(
            url_map['url'],
            url_map['view'],
            **distill_path_kwargs,
        )
    )

voting_urlpatterns = [
    path('voting/', views.voting_index, name='voting_index'),
    path('voting/summary/', views.voting_view_summary, name='voting_view_summary'),
    path('voting/<int:ordering>/', views.voting_view, name='voting_view'),
    path('voting/<int:ordering>/launch/', views.voting_view_launch, name='voting_view_launch'),
    path('voting/<int:ordering>/answer/', views.voting_view_answer, name='voting_view_answer'),
    path('voting/<int:ordering>/results/', views.voting_view_results, name='voting_view_results'),
    path('voting/upload-form', views.upload_form_view, name='upload_form'),
]

urlpatterns = [
    path('', include(static_page_urlpatterns + voting_urlpatterns)),
]

oxfordconsultants/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('backend/', admin.site.urls),
    path('', include('frontend.urls')),
]

frontend/models.py
from django import forms
from django.db import models


class Insight(models.Model):
    title = models.CharField(max_length=140)
    text = models.TextField()
    tag = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    url = models.URLField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Testimonial(models.Model):
    author = models.CharField(max_length=140, blank=True)
    company_name = models.CharField(max_length=140, blank=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.author


class Upload(models.Model):
    file = models.FileField(upload_to='uploads/')
    name = models.CharField(max_length=100, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file_name

    @property
    def file_name(self):
        return str(self.file.url.split('/uploads/')[1])


class UploadForm(forms.ModelForm):
    name = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        fields = ('file', 'name')
        model = Upload
        labels = {
            'file': ''
        }


class PersonToken(models.Model):
    token = models.CharField(max_length=50)
    name = models.CharField(max_length=150)
    weight = models.IntegerField(default=0)
    is_chairman = models.BooleanField(default=False)
    questions_to_skip = models.ManyToManyField('Question', blank=True)

    def __str__(self):
        return self.name


class PossibleAnswer(models.Model):
    ordering = models.IntegerField(default=0)
    text = models.CharField(max_length=100)
    consensus = models.TextField(blank=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('ordering', )


class Question(models.Model):
    ordering = models.IntegerField(default=0)
    text = models.TextField()
    voting_stopped = models.BooleanField(default=False)
    next_resolution_launched = models.BooleanField(default=False)
    slug = models.SlugField(null=True)
    possible_answers = models.ManyToManyField(PossibleAnswer)
    consensus = models.ForeignKey(PossibleAnswer, on_delete=models.CASCADE, related_name='+', null=True, blank=True)
    stats = models.JSONField(default=dict)

    def __str__(self):
        return f"{self.slug}. {self.text}"


class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(PossibleAnswer, on_delete=models.CASCADE)
    person = models.ForeignKey(PersonToken, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.person.name} voted [{self.answer}] on [{self.question}]"

frontend/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=500, widget=forms.Textarea())
    email = forms.EmailField()
    phone = forms.CharField(max_length=500, widget=forms.Textarea())
    subject = forms.CharField(max_length=500, widget=forms.Textarea())
    message = forms.CharField(max_length=500, widget=forms.Textarea())

frontend/views.py
import operator

from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse

from frontend.forms import ContactForm
from frontend.models import Insight, Testimonial, Upload, UploadForm, Question, Vote, PossibleAnswer, PersonToken

services_list = [
    {
        'description': """
                We are well-placed and have the capability to advise on and facilitate speedy incorporation in Ghana of 
                all forms of corporate entities, such as limited liability and unlimited liability companies, companies 
                limited by guarantee, branch offices of foreign companies, sole proprietorships, and partnerships. 
                We also represent clients in their registration with the Ghana Investment Promotion Centre (GIPC), 
                Ghana Free Zones Board (GFZB), and sector-specific regulatory bodies such as the Minerals Commission, 
                the Petroleum Commission, etc. as necessary.
                """,
        'title': 'Entities Registration',
        'slug': 'entities-registration',
        'icon': '<i class="fas fa-signature fa-2x"></i>',
    },
    {
        'description': """
                    We have expertise in providing excellent company secretarial services and support (in both French and English) to the 
                    management and boards of directors of companies, board committees, and shareholders of small, medium and 
                    large companies, both internationally and locally, in conformity with best practices around the world. 
                    We also have significant experience of maintaining the corporate registered offices and statutory registers of 
                    clients, and of liaising with the Registrar- General’s Department to effect the myriad of changes that 
                    take place in the lifetime of a company.
                """,
        'title': 'Company Secretarial',
        'slug': 'company-secretarial',
        'icon': '<i class="fas fa-pen-nib fa-2x"></i>',
    },
    {
        'description': """
                        We provide seamless business tax advisory services to our clients, from tax planning and financial
                         accounting to tax compliance. We also assist with registration with the relevant tax authorities
                          for companies’ income tax (IT) and value added tax (VAT), monthly calculation and remittance of
                           withholding tax (WHT) and VAT, review and submit IT returns, and conduct tax compliance review
                            of companies’ tax and accounting records, covering VAT, WHT, and employee-related taxes.
                    """,
        'title': 'Tax Advisory & Allied Services',
        'slug': 'tax-advisory-allied-services',
        'icon': '<i class="fas fa-coins fa-2x"></i>',
    },
    {
        'description': """
                    We provide advice on corporate governance, and ensure that our clients follow sound corporate 
                    governance practices to ensure accountability, fairness and transparency in their 
                    relationships with their different stakeholders.
                """,
        'title': 'Corporate Governance',
        'slug': 'corporate-governance',
        'icon': '<i class="fas fa-building fa-2x"></i>',
    },
    {
        'description': """
                    We have expertise in navigating the maze of regulatory and other requirements for doing 
                    business in Ghana in industries such as insurance, telecommunications, and the downstream and 
                    upstream petroleum sectors.
                """,
        'title': 'Compliance',
        'slug': 'compliance',
        'icon': '<i class="fas fa-registered fa-2x"></i>',
    },
    {
        'description': """
                        We have expertise and extensive experience in providing immigration advice and support to 
                        both individuals and companies. From work/ residence permits and dual citizenship applications, 
                        to indefinite leave to remain and right of abode applications, we assist individuals to 
                        regularize their stay in Ghana.
                    """,
        'title': 'Immigration',
        'slug': 'immigration',
        'icon': '<i class="fas fa-plane fa-2x"></i>',
    },
    {
        'description': """
                    For added convenience and speed in commencing business, you can purchase a ready-made company from us.
                    """,
        'title': 'Shelf companies',
        'slug': 'shelf-companies',
        'icon': '<i class="fas fa-archway fa-2x"></i>',
    },
    {
        'description': """
                    We advise on the liquidation of companies that no longer intend to continue in business, 
                    and provide experienced liquidators to handle the process.
                """,
        'title': 'Liquidation',
        'slug': 'liquidation',
        'icon': '<i class="fas fa-coins fa-2x"></i>',
    },
    {
        'description': """
                    From personal to business and official documents, we provide professional oral and written 
                    translation services in French and English.
                """,
        'title': 'Translation',
        'slug': 'translation',
        'icon': '<i class="fas fa-language fa-2x"></i>',
    },
    {
        'description': """
                       We provide nominee directors and shareholders for companies and individuals.
                   """,
        'title': 'Nominee Services',
        'slug': 'nominee-services',
        'icon': '<i class="fas fa-anchor fa-2x"></i>',
    },
    {
        'description': """
                    We provide a suite of human resource services as follows: compensation and benefits administration, 
                    recruitment, job evaluation, performance management, and payroll compliance.
                """,
        'title': 'Human Resources',
        'slug': 'human-resources',
        'icon': '<i class="fas fa-user-circle fa-2x"></i>',
    },
]


def index_view(request):
    context = {
        'banners': [
            {
                'src': '/static/images/banner-image-2.jpg',
                'text': '...seamless corporate solutions',
                'cta_text': 'Learn more',
            }
        ],
        'services': services_list,
        'insights': Insight.objects.filter(is_active=True)
    }
    return render(request, 'frontend/index.html', context)


def about_view(request):
    return render(request, 'frontend/about.html')


def contact_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            send_mail(
                f"[ContactPage] {contact_form.cleaned_data.get('subject')}",
                f"Name: {contact_form.cleaned_data.get('name')}\n"
                f"Email: {contact_form.cleaned_data.get('email')}\n"
                f"Phone: {contact_form.cleaned_data.get('phone')}\n\n"
                f"Message: {contact_form.cleaned_data.get('message')}\n",
                'contact-us-page@oxfordconsultantsgh.com',
                ['akuaa@oxfordconsultantsgh.com'],
                fail_silently=False,
            )
            messages.success(request, 'Message has successfully been submitted')
        pass
    else:
        contact_form = ContactForm()
    context = {
        'contact_form': contact_form
    }
    return render(request, 'frontend/contact.html', context)


def get_services_list():
    for service in services_list:
        yield service['slug']


def services_view(request, slug):
    service = None
    for s in services_list:
        if s['slug'] == slug:
            service = s
            break
    context = {
        'service': service
    }
    return render(request, 'frontend/service.html', context)


def redirect_to_english(request):
    return redirect(reverse('frontend:home'))


def testimonials_view(request):
    context = {
        'testimonials': Testimonial.objects.all()
    }
    return render(request, 'frontend/testimonials.html', context)


def voting_index(request):
    context = {}
    return render(request, 'frontend/voting_index.html', context)


def voting_view(request, ordering):
    question = Question.objects.get(ordering=ordering)
    person = PersonToken.objects.get(token=request.GET.get('token').lower())
    if person.is_chairman and ordering == 1:
        return redirect(reverse('frontend:voting_view_results', args=(ordering, ))+f'?token={person.token}')
    context = {
        'question': question,
        'person': person
    }
    return render(request, 'frontend/voting_view.html', context)


def voting_view_answer(request, ordering):
    question = Question.objects.get(ordering=ordering)
    answer = PossibleAnswer.objects.get(id=int(request.GET.get('answer')))
    person = PersonToken.objects.get(token__iexact=str(request.GET.get('token')).strip())

    try:
        Vote.objects.get(question=question, person=person).delete()
    except:
        pass
    Vote.objects.get_or_create(question=question, person=person, answer=answer)
    return redirect(reverse('frontend:voting_view_results', args=(question.ordering,))+f'?token={person.token}')


def voting_view_launch(request, ordering):
    old_resolution = Question.objects.get(ordering=ordering-1)
    old_resolution.next_resolution_launched = True
    old_resolution.save()

    question = Question.objects.get(ordering=ordering)
    person = PersonToken.objects.get(token__iexact=str(request.GET.get('token')).strip())

    return redirect(reverse('frontend:voting_view_results', args=(question.ordering,))+f'?token={person.token}')


def voting_view_results(request, ordering):
    question = Question.objects.get(ordering=ordering)

frontend/templates/frontend/about.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block page_title %}
    About
{% endblock %}
{% block extra_head %}
    <style>
        .bg-service {
            background: url("{% static 'images/banner-image-4.jpg' %}");
            background-size: cover;
            background-position: bottom;
        }

        .bgoverlay {
            background: rgba(0, 0, 0, 0.8);
        }
    </style>

{% endblock %}
{% block content %}
    <section class="hero is-medium is-dark bg-service">
        <div class="hero-body ">
            <div class="container">
                <div>
                    {% include 'frontend/partials/oc_logo.html' %}
                </div>
                <br>
                <br>
                <div class="bgoverlay w3-padding-large w3-padding-32">
                    <h1 class="w3-xxxlarge">About us</h1>
                    <p class="w3-xlarge">
                        Oxford Consultants is a young, dynamic, bi-lingual, progressive company established to offer
                        business support, strategic advisory and consultancy services with a full spectrum of
                        capabilities in
                        a myriad of areas of business, namely entities registrations, company secretarial services,
                        corporate
                        governance, compliance, immigration, nominee services, liquidation, tax advisory and allied
                        services,
                        translation services (French and English), and human resources services.
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

frontend/templates/frontend/contact.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block page_title %}
    Contact
{% endblock %}
{% block extra_head %}
    <style>
        .bg-service {
            background: url("{% static 'images/banner-image-4.jpg' %}");
            background-size: cover;
            background-position: bottom;
        }

        .bgoverlay {
            background: rgba(0, 0, 0, 0.8);
        }
    </style>

{% endblock %}
{% block content %}
    <section class="hero is-medium is-dark bg-service">
        <div class="hero-body ">
            <div class="container">
                <div>
                    {% include 'frontend/partials/oc_logo.html' %}
                </div>
                <br>
                <br>
                <div class="bgoverlay w3-padding-large w3-padding-32" style="max-width: 1000px;">
                    <form class="w3-xlarge" method="post">
                        {% csrf_token %}
                        <h1 class="w3-xxxlarge">Contact us</h1>
                        <br>
                        <div class="field is-horizontal">
                            <div class="field-body">
                                <div class="field">
                                    <label class="label w3-text-white w3-large">From *</label>
                                    <p class="control is-expanded has-icons-left">
                                        <input class="input" type="text" placeholder="Name" name="name" required>
                                        <span class="icon is-small is-left">
                                          <i class="fas fa-user"></i>
                                        </span>
                                    </p>
                                </div>
                                <div class="field">
                                    <label class="label w3-text-white w3-large">Email *</label>
                                    <p class="control is-expanded has-icons-left">
                                        <input class="input is-success" type="email" placeholder="Email" name="email"
                                               required>
                                        <span class="icon is-small is-left">
                                          <i class="fas fa-envelope"></i>
                                        </span>
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="field is-horizontal">
                            <div class="field-body">
                                <div class="field is-expanded">
                                    <label class="label w3-text-white w3-large">Phone</label>
                                    <div class="field has-addons">
                                        <p class="control is-expanded has-icons-left">
                                            <input name="phone" class="input" type="tel"
                                                   placeholder="Your phone number">
                                            <span class="icon is-small is-left">
                                              <i class="fas fa-phone-alt"></i>
                                            </span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field is-horizontal">
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <label class="label w3-text-white w3-large">Subject *</label>
                                        <input name="subject" class="input" type="text"
                                               placeholder="e.g. Inquiries, Opportunity, etc" required>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="field is-horizontal">

                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <label class="label w3-text-white w3-large">Message *</label>
                                        <textarea name="message" class="textarea"
                                                  placeholder="Explain how we can help you" required>

                                        </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="field is-horizontal">
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <button class="button is-white" type="submit">
                                            Send message
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

frontend/templates/frontend/service.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block page_title %}
    {{ service.title }}
{% endblock %}
{% block extra_head %}
    <style>
        .bg-service {
            background: url("{% static 'images/banner-image-4.jpg' %}");
            background-size: cover;
            background-position: bottom;
        }

        .bgoverlay {
            background: rgba(0, 0, 0, 0.8);
        }
    </style>

{% endblock %}
{% block content %}
    <section class="hero is-medium is-dark bg-service">
        <div class="hero-body ">
            <div class="container">
                <div>
                    {% include 'frontend/partials/oc_logo.html' %}
                </div>
                <br>
                <br>
                <div class="bgoverlay w3-padding-large w3-padding-32">
                    <h1 class="w3-xxxlarge">{{ service.title }}</h1>
                    <p class="w3-xlarge">
                        {{ service.description }}
                    </p>
                    <br>
                    <br>
                    <v-btn rounded x-large>Contact us</v-btn>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

frontend/templates/frontend/services.html
{% extends 'frontend/base.html' %}
{% block page_title %}
    {{ service.title }}
{% endblock %}
{% block content %}
    Services
{% endblock %}

frontend/templates/frontend/standard_page.html
{% extends 'frontend/base.html' %}
{% load static wagtailimages_tags wagtailcore_tags %}
{% block content %}
    <div class="w3-content w3-large w3-padding-32 w3-container">
        {{ page.body|linebreaksbr }}
    </div>
{% endblock %}

frontend/templates/frontend/voting_index.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block page_title %}
    {{ service.title }}
{% endblock %}
{% block content %}
    <section class="hero is-medium">
        <div class="hero-body">
            <form method="get" action="{% url 'frontend:voting_view' 1 %}" class="container w3-padding-64 w3-center" style="max-width: 500px;">
                <h1 class="w3-xxlarge w3-padding-16">What is your token?</h1>
                <input name="token" type="text" class="input is-large is-rounded is-black">
                <br>
                <br>
                <button class="button is-rounded is-black is-large" type="submit">
                    Submit
                </button>
            </form>
        </div>
    </section>
{% endblock %}

frontend/templates/frontend/voting_view.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block page_title %}
    {{ service.title }}
{% endblock %}
{% block content %}
    <section class="hero is-medium">
        <div class="hero-body">
            <div class="container w3-padding-64 w3-center" style="max-width: 800px;margin: auto">
                <h1 class="w3-xlarge w3-padding-16">
                    Resolution {{ question.slug }}:
                    {{ question.text }}
                </h1>
                {% if not person.is_chairman %}
                    {% if question in person.questions_to_skip.all %}
                        <a style="margin: 5px;" href="{% url 'frontend:voting_view_results' question.ordering %}?token={{ person.token }}" class="button is-rounded w3-border-black is-large w3-border">
                            <h6>Skip</h6>
                        </a>
                    {% else %}
                        {% for possible_answer in question.possible_answers.all %}
                            <a style="margin: 5px;" href="{% url 'frontend:voting_view_answer' question.ordering %}?token={{ person.token }}&answer={{ possible_answer.id }}" class="button is-rounded w3-border-black is-large w3-border" type="submit">
                                <h6>{{ possible_answer.text }}</h6>
                            </a>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

frontend/templates/frontend/voting_view_results.html
{% extends 'frontend/base.html' %}
{% load static humanize %}
{% block page_title %}
    {{ service.title }}
{% endblock %}
{% block content %}
    <section class="hero is-medium">
        <div class="hero-body">
            <div class="container w3-padding-64 w3-center" style="max-width: 800px;margin: auto">
                <h1 class="w3-xlarge">
                    Resolution {{ question.slug }}:
                    {{ question.text }}
                </h1>
                <br>
                {% if question.voting_stopped %}
                    <br>
                    <div class="table-container">
                        <table class="table is-fullwidth is-bordered">
                            <thead>
                            <tr>
                                <th class="text-left">
                                    Vote
                                </th>
                                <th class="text-left">
                                    Number of votes
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ winner.text }}</td>
                                <td>{{ winner_votes|intcomma }}</td>
                            </tr>
                            <tr>
                                <td>{{ loser.text }}</td>
                                <td>{{ loser_votes|intcomma }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <br>

                    <h1 class="w3-xxlarge w3-text-green">
                        Consensus: {{ winner.consensus|lower }}
                    </h1>
                    <br>
                    {% if person.is_chairman and next %}
                        <a href="{% url 'frontend:voting_view_launch' next %}?token={{ person.token }}"
                           class="button is-rounded w3-black is-medium w3-border" type="submit">
                            <h6>Launch voting on next resolution</h6>
                        </a>
                    {% elif person.is_chairman and not next %}
                        <a href="{% url 'frontend:voting_view_summary' %}?token={{ person.token }}"
                           class="button is-rounded w3-black is-medium w3-border" type="submit">
                            <h6>Voting summary</h6>
                        </a>
                    {% endif %}
                {% else %}
                    <div class="w3-padding-large w3-green w3-round-large w3-large w3-padding-24">
                        Voting in progress. This page will automatically refresh with results when voting has ended
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}
{% block extra_body %}
    {% if question.voting_stopped and not person.is_chairman %}
        {% if question.next_resolution_launched %}
            <script>
                {% if next is False%}
                    setTimeout(() => {
                        window.location.href = '{% url 'frontend:voting_view_summary'  %}'
                    }, 1)
                {% else %}
                    setTimeout(() => {
                        window.location.href = '{% url 'frontend:voting_view' next %}?token={{ person.token }}'
                    }, 1)
                {% endif %}
            </script>
        {% else %}
            <script>
                setTimeout(() => {
                    window.location.href = window.location.href
                }, 10000)
            </script>
        {% endif %}

    {% elif question.voting_stopped and person.is_chairman %}
    {% else %}
        <script>
            setTimeout(() => {
                window.location.href = window.location.href
            }, 10000)
        </script>
    {% endif %}
{% endblock %}